### ISSUE TITLE
The coverage-helper::test doesn't work with tokio::test

### ISSUE THREAD

**Issue by Phoenix500526** [taiki-e/coverage-helper#2]
Hi, @taiki-e. 

Currently, the implementation of coverage_helper replaces `std::test` with `coverage_helper::test`. However, this approach doesn't work for `tokio::test`. Given that `tokio::test` is widely used, shall we support `tokio::test` in this crate?

IMO, we can provide a `tokio` module in `coverage_helper`, like:
```Rust
mod test{
    use coverage_helper::{tokio, test};
    #[test]
    fn test_foo() {...}

    #[tokio::test]
    async fn test_bar() {...}
}
```

What do you think? If this approach is feasible, I can do some contributions.

**Comment by taiki-e** [comment]
As said in https://github.com/taiki-e/cargo-llvm-cov/issues/273, tokio::test refers ::core::prelude::v1::test, so it's not working with coverage_helper.

The most desirable fix is to change libtest so that the test attribute gets no_coverage, and the second most desirable is to make the change on the tokio side.

**Comment by taiki-e** [comment]
This problem may have been resolved by tokio-macros 2.3.0, which includes https://github.com/tokio-rs/tokio/pull/6497.

**Comment by gmli** [comment]
And so, what are we supposed to write in the tests using `#[tokio::test]` ?

EDIT : ok I understand, the version 2.3.0 of tokio-macros may have solved it without any change. I’ve updated to tokio 1.40.0 and the problem remains.

**Comment by bitcapybara** [comment]
any update?

**Comment by taiki-e** [comment]
No update on this issue, but the `#[coverage]` attribute itself has been improved and I believe most of the use cases for this crate will be replaced by it: https://github.com/taiki-e/cargo-llvm-cov/issues/123#issuecomment-2423715856

**Comment by taiki-e** [comment]
#[coverage(off)] attribute has been stabilized in https://github.com/rust-lang/rust/pull/130766 (will be included in Rust 1.85).

I will deprecate coverage-helper in favor of the pattern that is now documented in cargo-llvm-cov: https://github.com/taiki-e/cargo-llvm-cov/issues/123#issuecomment-2552149677


> If you want to ignore all `#[test]`-related code, you can use module-level `#[coverage(off)]` attribute:
>
> ```rust
> #[cfg(test)]
> #[cfg_attr(coverage, coverage(off))]
> mod tests {
>     // ...
> }
> ```
> 
> cargo-llvm-cov excludes code contained in the directory named `tests` from the report by default, so you can also use it instead of `#[coverage(off)]` attribute.
